# Page Rank
PageRank adalah salah satu algoritma yang digunakan oleh mesin pencari Google untuk menentukan peringkat halaman web dalam hasil pencarian. Algoritma ini mempertimbangkan faktor-faktor seperti kualitas dan jumlah tautan yang mengarah ke halaman tersebut untuk menentukan sejauh mana halaman web relevan dan otoritatif. PageRank dirancang untuk membantu pengguna menemukan konten yang paling relevan dan berkualitas tinggi saat mereka melakukan pencarian di internet.

# Algoritma Page Rank
1. Analisis Tautan: Algoritma memulai dengan menganalisis struktur tautan di web. Ia melihat semua tautan dari satu halaman ke halaman lain di internet.
2. Nilai Awal: Setiap halaman web awalnya diberi nilai peringkat yang sama.
3. Perhitungan Iteratif:
*  Untuk setiap halaman 𝑃, PageRank mendistribusikan nilai peringkat dari
𝑃 ke semua halaman yang ditautkan olehnya.
*  Jumlah nilai peringkat yang diberikan dari 𝑃 ke sebuah halaman yang ditautkannya sebanding dengan jumlah tautan keluar dari 𝑃.
*  Proses ini diulang secara iteratif hingga nilai peringkat stabil.
4. Faktor Redaman: Untuk memperhitungkan kemungkinan bahwa pengguna mungkin melompat secara acak ke halaman lain alih-alih mengikuti tautan diperkenalkan faktor redaman 𝑑 Faktor ini biasanya diatur sekitar 0,85. Rumus PageRank adalah:





\begin{equation}
PR(P_i) = \frac{1 - d}{N} + d \sum_{P_j \in M(P_i)} \frac{PR(P_j)}{L(P_j)}
\end{equation}

#### komputasi untuk menghitung pagerank
(gunakan error untuk menghentikan literasi
menggunakan root sum square error)

In [ ]:
import numpy as np

def pagerank(A, d=0.85, tol=1e-6, max_iter=100):
    n = len(A)
    M = np.zeros((n, n))
    for i in range(n):
        row_sum = sum(A[i])
        if row_sum == 0:
            M[i] = np.ones(n) / n
        else:
            M[i] = A[i] / row_sum

    v = np.ones(n) / n
    last_v = np.ones(n) * np.inf

    iter = 0
    while np.sqrt(np.sum((v - last_v) ** 2)) > tol and iter < max_iter:
        last_v = v
        v = d * np.dot(M, v) + (1 - d) / n
        iter += 1

    return v

# Example usage:
# Adjacency matrix
A = np.array([[0, 0, 1, 1/2],
              [1/3, 0, 0, 0],
              [1/3, 1/2, 0, 1/2],
              [1/3, 1/2, 0, 0]])

# Calculate PageRank
pagerank_result = pagerank(A)
print("PageRank:", pagerank_result)

# Another example
A2 = np.array([[0, 1, 1, 0],
               [1, 0, 1, 1],
               [1, 1, 0, 1],
               [0, 1, 1, 0]])

pagerank_result2 = pagerank(A2)
print("PageRank for second example:", pagerank_result2)


PageRank: [0.25 0.25 0.25 0.25]
PageRank for second example: [0.25 0.25 0.25 0.25]


# Contoh Penerapan untuk Mencari Pagerank dalam Code

In [ ]:
import numpy as np
A = np.array([[0,0,1,1/2], [1/3, 0 ,0 ,0], [1/3,1/2,0,1/2],[1/3,1/2,0,0]])
v = np.array([[0.25], [0.25], [0.25], [0.25]])
print ('A x v=\n', A@v)
print ('A^2 x v=\n', A@A@v)
print ('A x (Av)=\n', A@(A@v))
print ('A^3 x v=\n', A@A@A@v)
print ('A^4 x v=\n', A@A@A@A@v)
print ('A^5 x v=\n', A@A@A@A@A@v)
print ('A^6 x v=\n', A@A@A@A@A@A@v)
print ('A^7 x v=\n', A@A@A@A@A@A@A@v)
print ('A^8 x v=\n', A@A@A@A@A@A@A@A@v)

A x v=
 [[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
A^2 x v=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A x (Av)=
 [[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
A^3 x v=
 [[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
A^4 x v=
 [[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
A^5 x v=
 [[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
A^6 x v=
 [[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
A^7 x v=
 [[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
A^8 x v=
 [[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]


In [2]:
np as array
A = ([[2,3],[3,4]])
B = ([[2,4],[5,6]])
import as ampty
print

SyntaxError: invalid syntax (<ipython-input-2-83da2d9a7d46>, line 1)