#**Determinan**





Determinan adalah suatu bilangan real yang diperoleh dari suatu proses dengan aturan tertentu terhadap matriks bujur sangkar
. Secara lebih umum, determinan merupakan nilai skalar yang hanya memiliki besaran atau nilai, yang dihitung dari unsur-unsur suatu matriks persegi
. Dalam matematika, determinan adalah sebuah fungsi tertentu yang menghubungkan suatu bilangan real dengan suatu matriks bujur sangkar
.

Determinan matriks A ditulis dengan tanda det(A), det A, atau |A|, dan dapat dianggap sebagai faktor penskalaan transformasi yang digambarkan oleh matriks
. Nilai determinan ini dapat menentukan beberapa sifat dari matriks dan pemetaan linear yang direpresentasikan oleh matriks tersebut.

Dalam konteks matriks, determinan juga dapat dihitung dengan menggunakan metode ekspansi kofaktor baris pertama
. Jika nilai determinan suatu matriks bujur sangkar adalah 0, maka matriks tersebut disebut singular, yang berarti matriks tersebut tidak memiliki invers. Sebaliknya, jika nilai determinan matriks bujur sangkar tidak sama dengan 0, maka matriks tersebut disebut nonsingular, yang artinya matriks tersebut memiliki invers
.

#**Syarat mencari determinan matriks**

Determinan dari suatu matriks dapat dihitung dengan beberapa syarat yang perlu dipenuhi. Berikut adalah beberapa syarat umum untuk mencari determinan matriks:

Matriks Persegi: Determinan hanya dapat dihitung untuk matriks yang merupakan matriks persegi, yaitu matriks yang memiliki jumlah baris sama dengan jumlah kolomnya
.
Ukuran Matriks: Semakin besar ukuran matriks, semakin kompleks cara mencari determinannya. Matriks ordo 2x2 merupakan matriks paling sederhana, sehingga cara mencari determinannya juga sederhana
.
Metode Perhitungan: Terdapat beberapa metode untuk menghitung determinan matriks, seperti metode pertama yang dihitung dengan rumus tertentu, dan metode kedua yang mereduksi determinan menjadi ordo 2
.
Matriks Invers: Determinan matriks juga berkaitan dengan matriks invers. Misalnya, jika suatu matriks bujur sangkar A dikalikan terhadap inversnya yaitu matriks bujur sangkar A1, maka menghasilkan matriks identitas pada operasi perkalian matriks
.

Dengan memenuhi syarat-syarat tersebut, determinan matriks dapat dihitung sesuai dengan rumus dan metode yang berlaku untuk matriks tersebut.

#**Sifat sifat determinan**

Determinan merupakan suatu nilai yang terkait dengan matriks dan memiliki beberapa sifat yang penting dalam matematika. Beberapa sifat-sifat determinan yang perlu diketahui antara lain:

1. Sifat Determinan Matriks Identitas:

Identitas merupakan matriks diagonal, sehingga determinannya sama dengan hasil kali dari semua entri diagonalnya, yang semuanya bernilai 1. Sehingga, determinan dari matriks identitas adalah 1.

2. Sifat Determinan Matriks Transpose:

Determinan dari matriks transpose sama dengan determinan dari matriks aslinya, yaitu det(A) = det(A^T).

3. Sifat Determinan Matriks Skalar:

Jika A adalah matriks berukuran n x n, maka determinan dari kA adalah kn det(A), di mana k adalah skalar
.

4. Sifat Determinan Matriks Segitiga:

Jika A adalah matriks segitiga atas, segitiga bawah, atau diagonal, maka determinannya adalah hasil kali dari elemen-elemen diagonal utamanya, yaitu det(A) = a11a22a33...ann
.

5. Sifat Determinan Matriks Invers:

Determinan dari invers matriks A dapat dihitung dengan rumus det(A^-1) = 1/det(A).

6. Sifat Determinan Matriks Penjumlahan:

Determinan dari penjumlahan dua matriks A dan B sama dengan determinan dari matriks A ditambah determinan dari matriks B, yaitu det(A+B) = det(A) + det(B)
.

7. Sifat Determinan Matriks Perkalian:

Determinan dari hasil perkalian dua matriks A dan B sama dengan perkalian determinan matriks A dan B, yaitu det(AB) = det(A) * det(B)
.

In [1]:
import numpy as np

#fungsi mencari determinan
def det(matriks):
    return np.linalg.det(matriks)

print("Membuktikan bahwa determinan dari matriks identitas adalah 1")
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
print('Matriks A =\n', I)
print("determinan dari matriks i adalah",det(I))

print("perubahan baris pada matriks identitas untuk mencari determinannya")
I2=np.array([[1,0,0],[0,0,1],[0,1,0]])
print("determinan dari matriks i setelah diubah pertama kali adalah",det(I2))
I3=np.array([[0,1,0],[0,0,1],[1,0,0]])
print("determinan dari matriks i setelah diubah kedua kali adalah",det(I3),"\n")

print("mencari determinan c")
c = np.array([[1,2,1],[3,1,2],[2,1,2]])
print("determinan dari matriks c adalah",det(c).round())
d = np.array([[3,1,2],[1,2,1],[2,1,2]])
print("determinan dari matriks c setelah diubah pertama kali adalah",det(d).round())
e = np.array([[1,2,1],[2,4,2],[2,1,2]])
print("determinan dari matriks e adalah",det(e).round())
print("jika baris dikalikan dengan kelipatan maka hasilnya akan 0")
f = np.array([[1,2,1],[2,4,2],[2,4,3]])
print("determinan dari matriks f adalah",det(f).round())
g = np.array([[6,2,4],[2,4,2],[4,2,4]])
print("determinan dari matriks g adalah",det(g).round())#2^3(3)-> 2=konstanta, ^3=jumlah baris yang dikalikan dengan konstanta, (3)=hasil dari det(c)
a=np.array([[3,4],[2,1]])
print("determinan dari matriks a adalah",det(a).round())
h=np.array([[6,8],[4,2]])
print("determinan dari matriks h adalah",det(h).round()) #2^2(-5)=-20
i=np.array([[6,8],[2,1]])
print("determinan dari matriks i adalah",det(i).round()) #jika hanya satu baris saja c det(a) = 2(-5) = -10

print("\nmengalikan salah satu kolom ")
j=np.array([[6,4],[4,1]])
print("determinan dari matriks j adalah",det(j).round())#hasilnya bakal sama dengan yang salah satu baris saja yang dikalikan

Membuktikan bahwa determinan dari matriks identitas adalah 1
Matriks A =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
determinan dari matriks i adalah 1.0
perubahan baris pada matriks identitas untuk mencari determinannya
determinan dari matriks i setelah diubah pertama kali adalah -1.0
determinan dari matriks i setelah diubah kedua kali adalah 1.0 

mencari determinan c
determinan dari matriks c adalah -3.0
determinan dari matriks c setelah diubah pertama kali adalah 3.0
determinan dari matriks e adalah 0.0
jika baris dikalikan dengan kelipatan maka hasilnya akan 0
determinan dari matriks f adalah 0.0
determinan dari matriks g adalah 24.0
determinan dari matriks a adalah -5.0
determinan dari matriks h adalah -20.0
determinan dari matriks i adalah -10.0

mengalikan salah satu kolom 
determinan dari matriks j adalah -10.0


In [2]:
import numpy as np

A = np.array([[1,0],[0,1]])
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
C = np.array([[1,0,0],[0,0,1],[0,1,0]])
D = np.array([[0,1,0],[0,0,1],[1,0,0]])
E = np.array([[1,2,1],[3,1,2],[2,1,2]])
F = np.array([[3,1,2],[1,2,1],[2,1,2]])
G = np.array([[1,2,1],[2,4,2],[2,1,2]])
H = np.array([[1,2,2],[2,4,4],[1,2,3]])
I = np.array([[6,2,4],[2,4,2],[4,2,4]])
J = np.array([[3,4],[2,1]])
K = np.array([[6,8],[4,2]])
L = np.array([[2*3,2*4],[2,1]])
M = np.array([[2*3,4],[2*2,1]])
N = np.array([[4,1],[2,1]])
O = np.array([[7,5],[2,1]])
P = np.array([[2,3,2],[0,2,2],[0,0,2]])
Q = np.array([[2,1],[1,1]])
R = np.array([[1,1],[1,1]])
S = np.array([[3,3],[2,2]])


print(f"Matrix A (Identitas)=\n{A}")
print(f"Matrix B (Identitas)=\n{B}")
print(f"Matrix C =\n{C}")
print(f"Matrix D =\n{D}")
print(f"Matrix E =\n{E}")
print(f"Matrix F =\n{F}")
print(f"Matrix G =\n{G}")
print(f"Matrix H =\n{H}")
print(f"Matrix I =\n{I}")
print(f"Matrix J =\n{J}")
print(f"Matrix K =\n{K}")
print(f"Matrix L =\n{L}")
print(f"Matrix M =\n{M}")
print(f"Matrix N =\n{N}")
print(f"Matrix O =\n{O}")
print(f"Matrix P =\n{P}")
print(f"Matrix Q =\n{Q}")
print(f"Matrix R =\n{R}")
print(f"Matrix S =\n{S}")

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_F = np.linalg.det(F)
det_G = np.linalg.det(G)
det_H = np.linalg.det(H)
det_I = np.linalg.det(I)
det_J = np.linalg.det(J)
det_K = np.linalg.det(K)
det_L = np.linalg.det(L)
det_M = np.linalg.det(M)
det_N = np.linalg.det(N)
det_O = np.linalg.det(O)
det_P = np.linalg.det(P)
det_Q = np.linalg.det(Q)
det_R = np.linalg.det(R)
det_S = np.linalg.det(S)

print("")
print(f"Determinan Matrix A =\n{det_A}")
print("")
print(f"Determinan Matrix B =\n{det_B}")
print("")
print(f"Determinan Matrix C =\n{det_C}")
print("")
print(f"Determinan Matrix D =\n{det_D}")
print("")
print(f"Determinan Matrix E =\n{det_E}")
print("")
print(f"Determinan Matrix F =\n{det_F}")
print("")
print(f"Determinan Matrix G =\n{det_G}")
print("")
print(f"Determinan Matrix H =\n{det_H}")
print("")
print(f"Determinan Matrix I =\n{det_I}")
print("")
print(f"Determinan Matrix J =\n{det_J}")
print("")
print(f"Determinan Matrix K =\n{det_K}")
print("")
print(f"Determinan Matrix L =\n{det_L}")
print("")
print(f"Determinan Matrix M =\n{det_M}")
print("")
print(f"Determinan Matrix N =\n{det_N}")
print("")
print(f"Determinan Matrix O =\n{det_O}")
print("")
print(f"Determinan Matrix P =\n{det_P}")
print("")
print(f"Determinan Matrix Q =\n{det_Q}")
print("")
print(f"Determinan Matrix R =\n{det_R}")
print("")
print(f"Determinan Matrix S =\n{det_S}")

Matrix A (Identitas)=
[[1 0]
 [0 1]]
Matrix B (Identitas)=
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix C =
[[1 0 0]
 [0 0 1]
 [0 1 0]]
Matrix D =
[[0 1 0]
 [0 0 1]
 [1 0 0]]
Matrix E =
[[1 2 1]
 [3 1 2]
 [2 1 2]]
Matrix F =
[[3 1 2]
 [1 2 1]
 [2 1 2]]
Matrix G =
[[1 2 1]
 [2 4 2]
 [2 1 2]]
Matrix H =
[[1 2 2]
 [2 4 4]
 [1 2 3]]
Matrix I =
[[6 2 4]
 [2 4 2]
 [4 2 4]]
Matrix J =
[[3 4]
 [2 1]]
Matrix K =
[[6 8]
 [4 2]]
Matrix L =
[[6 8]
 [2 1]]
Matrix M =
[[6 4]
 [4 1]]
Matrix N =
[[4 1]
 [2 1]]
Matrix O =
[[7 5]
 [2 1]]
Matrix P =
[[2 3 2]
 [0 2 2]
 [0 0 2]]
Matrix Q =
[[2 1]
 [1 1]]
Matrix R =
[[1 1]
 [1 1]]
Matrix S =
[[3 3]
 [2 2]]

Determinan Matrix A =
1.0

Determinan Matrix B =
1.0

Determinan Matrix C =
-1.0

Determinan Matrix D =
1.0

Determinan Matrix E =
-3.000000000000001

Determinan Matrix F =
3.000000000000001

Determinan Matrix G =
0.0

Determinan Matrix H =
0.0

Determinan Matrix I =
24.000000000000014

Determinan Matrix J =
-5.000000000000001

Determinan Matrix K =
-19.9999999999